name: Build Android APK
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        
    - name: List project files
      run: |
        echo "=== Project Structure ==="
        find . -type f -name "*.kt" -o -name "*.xml" -o -name "*.gradle*" -o -name "gradlew*" | head -20
        echo "=== Gradle files ==="
        ls -la
        echo "=== App files ==="
        ls -la app/ || echo "No app folder"
        ls -la app/src/ || echo "No app/src folder"
        
    - name: Create missing files if needed
      run: |
        # Create essential files if they're missing
        if [ ! -f "settings.gradle.kts" ]; then
          echo 'include(":app")' > settings.gradle.kts
        fi
        
        if [ ! -f "app/build.gradle.kts" ]; then
          mkdir -p app
          cat > app/build.gradle.kts << 'EOF'
          plugins {
              id("com.android.application")
              kotlin("android")
          }
          android {
              compileSdk = 34
              defaultConfig {
                  applicationId = "com.example.autoqanswer"
                  minSdk = 24
                  targetSdk = 34
              }
              buildTypes {
                  getByName("debug") {
                      isMinifyEnabled = false
                  }
              }
          }
          dependencies {
              implementation("androidx.core:core-ktx:1.9.0")
              implementation("androidx.appcompat:appcompat:1.6.1")
          }
          EOF
        fi
        
    - name: Setup Gradle
      run: |
        # Download Gradle wrapper
        wget -q https://github.com/gradle/gradle/raw/master/gradle/wrapper/gradle-wrapper.jar
        mkdir -p gradle/wrapper
        mv gradle-wrapper.jar gradle/wrapper/
        
        # Create gradle wrapper properties
        cat > gradle/wrapper/gradle-wrapper.properties << 'EOF'
        distributionBase=GRADLE_USER_HOME
        distributionPath=wrapper/dists
        distributionUrl=https\://services.gradle.org/distributions/gradle-8.0-bin.zip
        zipStoreBase=GRADLE_USER_HOME
        zipStorePath=wrapper/dists
        EOF
        
        # Create gradlew script
        cat > gradlew << 'EOF'
        #!/bin/sh
        exec java -cp gradle/wrapper/gradle-wrapper.jar org.gradle.wrapper.GradleWrapperMain "$@"
        EOF
        chmod +x gradlew
        
    - name: Try to build
      run: |
        ./gradlew tasks --no-daemon || echo "Gradle tasks failed"
        ./gradlew assembleDebug --no-daemon --stacktrace
